### ISSUE TITLE
Add gathering timeout

### ISSUE THREAD

**Issue by lgrahl** [rawrtc/rawrtc#104]
Sometimes, the ICE gatherer doesn't stop gathering. Although this might be a bug on itself (possible already resolved by the code base of #69), the user application should be able to configure a timeout.

**Comment by jlaine** [comment]
After playing with `peer-connection` quite a lot, I've noticed that it fails to finish gathering about half the time. However if I remove the second STUN server `"stun:stun1.l.google.com:19302"` it seems to work reliably.

**Comment by lxlenovostar** [comment]
`rawrtc_ice_gatherer_create `don't have any parameter with timeout. So If we want to just cancel  a long gatherer not close gather, we should use `timer` and  `rawrtc_ice_gatherer_close`, This is right? @lgrahl

**Comment by jlaine** [comment]
Even without a specific "gathering" timer I would expect it to fail at the STUN level: there should be a retry limit on the transactions, no?

**Comment by lgrahl** [comment]
I think there is an internal timer in re. I'm not entirely sure what's causing this issue but if it bothers you two, then I guess I should look into it (even though #69 probably has a fix for this).

> So If we want to just cancel a long gatherer not close gather, we should use `timer` and `rawrtc_ice_gatherer_close`

But closing the gatherer will flush all candidates. You probably don't want that.

(This issue here is only of importance when waiting for the end-of-candidates indicator. Trickle ICE should work fine.)

**Comment by lgrahl** [comment]
This is partially resolved by 4114045126e407a41d22f818c834a78a700087fa but that is not in the master branch at the moment. Hopefully later this week.

**Comment by lxlenovostar** [comment]
I test rawrtc by rawrtc-terminal, and stun/turn server is coturn(https://github.com/coturn/coturn). 

1.rawrtc use the way of Trickle ICE, So we can build datachannel before ICE gatherer state: complete.

2.The network communication process of the ICE gatherer is:
![_031518_072310_pm](https://user-images.githubusercontent.com/444868/37460604-ae298b7c-2886-11e8-85d9-0ae122b33507.jpg)
I notice interval almost is: 0, 0.5, 1, 2, 4, 8, 10, 6, But I read the source code, we have only one interval:
`    stun_keepalive_enable(stun_keepalive, rawrtc_default_config.stun_keepalive_interval);`

@lgrahl  
question 1:
I know we use `stun_request` which send Binding Request, How to  implement send stun packet in the change interval ?

question2:
What condition triggers gather complete?
I think the key point is:
```
static void stun_response_handler(int err, uint16_t scode, const char *reason,
				  const struct stun_msg *msg, void *arg)
{
	struct stun_keepalive *ska = arg;
	struct stun_attr *attr;
	(void)reason;

	/* Restart timer */
	if (ska->interval > 0)
		tmr_start(&ska->tmr, ska->interval*1000, timeout, ska);

	if (err || scode) {
		/* Clear current mapped addr to force new notification */
		sa_set_in(&ska->curmap, 0, 0);

		goto out;
	}

	attr = stun_msg_attr(msg, STUN_ATTR_XOR_MAPPED_ADDR);
	if (!attr)
		attr = stun_msg_attr(msg, STUN_ATTR_MAPPED_ADDR);

	if (!attr) {
		err = ENOENT;
		goto out;
	}

	if (!sa_cmp(&ska->curmap, &attr->v.sa, SA_ALL)) {
		ska->curmap = attr->v.sa;
		call_handler(ska, 0, &ska->curmap);
	}

 out:
	if (err)
		call_handler(ska, err, NULL);
}
```
`if (!sa_cmp(&ska->curmap, &attr->v.sa, SA_ALL)) { `  is the factor, This is right?
Thank you.

**Comment by lgrahl** [comment]
1. What you see there is a mix of retransmissions and normal STUN keepalive. See `rawrtc_default_config`:
    ```c
    .stun_config = {
        .rto = STUN_DEFAULT_RTO, // timeout with exponential backoff (500ms)
        .rc = STUN_DEFAULT_RC, // amount of total transmissions (7)
        .rm = STUN_DEFAULT_RM, // wait time after last transmission (16s)
        .ti = STUN_DEFAULT_TI, // reliable timeout (39500ms)
        .tos = 0x00, // type of service, doesn't matter here
    }
    ```
    The resulting send times are 0.0s, 0.5s, 1.5s, 3.5s, 7.5s, 15.5s, 31.5s and wait until 47.5s. These retransmissions only occur if there's no response, so your configuration might be incorrect.
    And then there's the normal STUN keepalive currently set to a 25s interval as you can see from the send times of 0.0s and 25.0s.

2. That code has nothing to do with the (ICE) gathering process. This returns once a STUN response has been received.

**Comment by lgrahl** [comment]
Note to myself: Re-enable the STUN keepalive towards STUN servers until the candidate pairing process has been started to keep the hole-punching process running.

**Comment by lxlenovostar** [comment]
I think stun server reply Bind Success in time,  Is this situation being retransmitted?  
@lgrahl   I will send pcap file to you by Gmail. 
Thank you.

**Comment by lgrahl** [comment]
@lxlenovostar I'll merge `separate-sctp-dc´ soon and then you can try again. If it's still an issue at that point, open a new issue.

**Comment by lxlenovostar** [comment]
ok, I will try.

**Comment by lxlenovostar** [comment]
hi  @lgrahl :
   I think you are right, Those packets should be retransmission packets。
