### ISSUE TITLE
Missing comma in peer_connection_description.c

### ISSUE THREAD

**Issue by JesApp** [rawrtc/rawrtc#111]
Line 38 of `peer_connection_description.c` needs a comma. You have already fixed that in commit c6c0130d572ac45df45b1608ed43fa71b462b498, but this bug is also present in release 0.2.1. 

Could you make a bug fix release, or cherry-pick that commit into the master branch?

**Comment by lgrahl** [comment]
[Done!](https://github.com/rawrtc/rawrtc/releases/tag/v0.2.2)

**Comment by JesApp** [comment]
Thanks!
