### ISSUE TITLE
Investigate worker thread compatibility

### ISSUE THREAD

**Issue by lgrahl** [rawrtc/rawrtc#112]
re supports `re_thread_init`. I'm quite sure at least the SCTP transport would break when used in two different threads.

**Comment by lgrahl** [comment]
See [this](https://github.com/creytiv/retest/blob/master/src/remain.c) how to use a worker thread.

**Comment by lxlenovostar** [comment]
In our live platform, I use  rawtc on openwrt/ARM,  I find build datachannel and send data by datachannel will spend too much time, I think this relate with the poor performance of hardware. So maybe we should use two threads, one thread get video by HTTP and build datachannel, and the other thread send data by datachannel, or more threads send data by datachannel.   This need datachannel move from  re_main() to anthor re_main(). This is possible ? @lgrahl

**Comment by lgrahl** [comment]
I have never done it, so all I can tell you is: Try it and let us know how it turned out.

**Comment by lxlenovostar** [comment]
Let rawrtc in multi-process? This is a good and feasible way?  @lgrahl

**Comment by lgrahl** [comment]
I would always avoid using multiple processes unless there is a very good reason for it.

**Comment by lxlenovostar** [comment]
Each proccess run a rawrtc, this can use multiple cpu core.

**Comment by lgrahl** [comment]
If your use case is limited by a single CPU core, then you can of course work around it by using multiple processes.

**Comment by lgrahl** [comment]
I investigated and here are my results:

There will be no worker thread compatibility when merging #109. Thus, one may not use `re_thread_init` to create worker threads and run `re_main` (another event loop) inside of it when using data channels. But I also don't believe there is any significant gain from it since usrsctp will only use one thread anyway. If you need to do CPU-intensive tasks, use [re's thread safe message queues](http://www.creytiv.com/doxygen/re-dox/html/mqueue_8c.html). However, if this creates an issue for someones use case, I'll listen and we'll see if it needs to be re-introduced.
