### ISSUE TITLE
How to get the time of send data?

### ISSUE THREAD

**Issue by lxlenovostar** [rawrtc/rawrtc#129]
The send process is:
```
rawrtc_data_channel_send
                        ==>channel_send_handler
                                ==> rawrtc_sctp_transport_send
                                          ==>  sctp_transport_send 
                                                    ==> usrsctp_sendv

```
When `usrsctp_sendv `return, the data just put in sctp buffer.   I want to count the time which the data arrives at the opposite peer , How to get it?
Thank you.

**Comment by lgrahl** [comment]
There's no API surface for that. However, we could expose the RTT as part of a statistics API.

**Comment by lxlenovostar** [comment]
I don't find any API about get RTT in [usrsctp.](https://github.com/sctplab/usrsctp/blob/master/Manual.md) Please explain the details, thank you.

**Comment by lgrahl** [comment]
See https://tools.ietf.org/html/rfc6458#section-8.2.2
