### ISSUE TITLE
How to improve the success rate of P2P hole punching？

### ISSUE THREAD

**Issue by lxlenovostar** [rawrtc/rawrtc#131]
we build P2P connection by ICE/stun.  Is there any other reason for P2P failure except for NAT type?

**Comment by lgrahl** [comment]
There may always be different reasons, such as bugs, very strict timeouts, etc. Do you have something specific in mind? Otherwise, I'd close this issue as it is very broad. :slightly_smiling_face:

**Comment by lgrahl** [comment]
I think I answered the question how the success rate can be improved. Atm, there are a couple of bugs (#64, #82, #104) associated to the gathering and connection setup phase. If you have specific issues in networks where another implementation works fine but RAWRTC doesn't, please open a new issue and add tracefiles.

**Comment by lxlenovostar** [comment]
If we set `gatherer->ice_config.enable_prflx = true` , I think we can improve the success rate of P2P hole punching. Why not set it in default?

**Comment by lgrahl** [comment]
Good question. Would you like to make a pull request for it? :slightly_smiling_face:

**Comment by lxlenovostar** [comment]
OK, I will do it.
