### ISSUE TITLE
Error running ./make-dependencies.sh

### ISSUE THREAD

**Issue by guypaskar** [rawrtc/rawrtc#133]
First, the readme file states cmake >= 3.2 but I think the latest version is 3.14 (I might be wrong but that's what I saw)

I'm getting this error when calling ./make-dependencies.sh (on mac os 10.13.6), gcc 9.1.0

[ 13%] Building C object usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_auth.c.o
error: error: error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
error: error: unknown warning optionunknown  '-Werror=format-truncation'warning  [-Werror,-Wunknown-warning-option]option 
'-Werror=format-truncation' [-Werror,-Wunknown-warning-option]unknown 
warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_crc32.c.o] Error 1make[2]: 
*** [usrsctplib/CMakeFiles/usrsctp-static.dir/netinet/sctp_cc_functions.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....make[2]: 
*** Waiting for unfinished jobs....
make[2]: make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o] Error 1*** [usrsctplib/CMakeFiles/usrsctp-static.dir/netinet/sctp_crc32.c.o] Error 1
make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_cc_functions.c.o] Error 1
make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_callout.c.o] Error 1
make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_asconf.c.o] Error 1
make[2]: *** [usrsctplib/CMakeFiles/usrsctp-static.dir/netinet/sctp_callout.c.o] Error 1
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
make[2]: *** [usrsctplib/CMakeFiles/usrsctp-static.dir/netinet/sctp_bsd_addr.c.o] Error 1
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Werror=format-truncation' [-Werror,-Wunknown-warning-option]
make[2]: *** [usrsctplib/CMakeFiles/usrsctp-static.dir/netinet/sctp_asconf.c.o] Error 1
make[2]: *** [usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_auth.c.o] Error 1
make[1]: *** [usrsctplib/CMakeFiles/usrsctp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [usrsctplib/CMakeFiles/usrsctp-static.dir/netinet/sctp_auth.c.o] Error 1
make[1]: *** [usrsctplib/CMakeFiles/usrsctp-static.dir/all] Error 2
make: *** [all] Error 2

**Comment by lgrahl** [comment]
I've reverted 5026dcb42b5cbffb979d1fa714e5f798730361f3 which should resolve this.

**Comment by guypaskar** [comment]
@lgrahl did not solve it.

**Comment by lgrahl** [comment]
I see, this is an issue as part of the usrsctp build system.

**Comment by lgrahl** [comment]
Checked again. There's nothing in the code any more that would lead to this particular error. Either you're seeing a different error in which case you can post it here or there are leftover build files. Make sure you have a clean repository (i.e. remove `build`).

---

> file states cmake >= 3.2 but I think the latest version is 3.14

14 is greater than 2. :slightly_smiling_face:

**Comment by lgrahl** [comment]
In any case, it's moot now since we've switched the build system and got rid of the dependencies script. :slightly_smiling_face:
