### ISSUE TITLE
Enable peer reflexive candidates

### ISSUE THREAD

**Issue by lgrahl** [rawrtc/rawrtc#134]
Has been disabled for now since the code base is not ready for them. It currently results in warnings and the newly found pairs will be dropped immediately. The code needs to be updated to allow for on-the-fly candidate helper creation.

**Comment by lxlenovostar** [comment]
If Chrome is in a symmetric network, and rawrtc is a full cone network.This scenes  can't build P2P, if I enable peer reflexive candidates, it work.  Is there a problem with those codes?

**Comment by lgrahl** [comment]
The problem is that the candidate helper struct is not available when finding a new peer reflexive candidate. I see a bunch of warnings in the output.

**Comment by lxlenovostar** [comment]
I have run rawrtc on one thousand linux box, prflx improve the success rate of P2P. 

> Has been disabled for now since the code base is not ready for them. It currently results in warnings and the newly found pairs will be dropped immediately. The code needs to be updated to allow for on-the-fly candidate helper creation.

Which function drop it? Please give  me some point! Thank you.

**Comment by lgrahl** [comment]
> I have run rawrtc on one thousand linux box, prflx improve the success rate of P2P.

Might be.

> Which function drop it? Please give me some point! Thank you.

https://github.com/rawrtc/rawrtc/blob/c6cd5dee377bcced61cd092fcbca9109698deffd/src/librawrtc/dtls_transport.c#L758

This function failed to find the helper during my tests.

**Comment by lxlenovostar** [comment]
> If Chrome is in a symmetric network, and rawrtc is a full cone network.This scenes can't build P2P, if I enable peer reflexive candidates, it work.

In this case, local candidate of rawrtc don't change, but remote candidate of rawrtc change, so it work

> If rawrtc is in a symmetric network, and Chrome is a full cone network.

In this case, local candidate of rawrtc change,` rawrtc_candidate_helper_find`  will return false.

This is right?

**Comment by lxlenovostar** [comment]
I try to fix it, please check it. [pull request](https://github.com/rawrtc/rawrtc/pull/138/commits/3a1b6aa211ee032723d96fb3ae0250e0a3df788e)
