### ISSUE TITLE
Resolve mDNS candidates

### ISSUE THREAD

**Issue by lgrahl** [rawrtc/rawrtc#135]
See https://tools.ietf.org/html/draft-ietf-rtcweb-mdns-ice-candidates-02

**Comment by AustinSchuh** [comment]
Chrome is now sending iceCandidates with this in them from what I can see.  I've got the terminal demo working, except it appears to crash when it hits this.

I'll try grabbing the changes in 147 and see if the commits there fix it.

rawrtc is so much easier to build than webrtc, especially for embedded platforms where I just want data channels.

**Comment by AustinSchuh** [comment]
Yup, I can confirm that the changes in #147 make it so this works with chrome.

**Comment by lgrahl** [comment]
I ran into some issues with Firefox when testing that branch but I think I just hit [that bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1691189) because most of our tools do not use trickle ICE. Guess I'll just merge it for now.

**Comment by lgrahl** [comment]
I'll delay a release until I (or someone else) tested with Firefox some more and GH actions has been set up. Could take a while since I'm busy atm. But building master should work just fine for now.

**Comment by AustinSchuh** [comment]
Thanks!  I'll also report back when I've gotten a chance to work with Firefox.
