### ISSUE TITLE
How to set candidate not in offer?

### ISSUE THREAD

**Issue by lxlenovostar** [rawrtc/rawrtc#150]
I test peer-connection, when I set offer and candiate in the same time, it can work.

`{"type":"offer","sdp":"v=0\r\no=- 3110157978395432486 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:KwOQ\r\na=ice-pwd:yPaeFKtxkTrXUy7xVhhRP15s\r\na=ice-options:trickle\r\na=fingerprint:sha-256 EA:A1:E7:BF:C9:8C:66:74:01:E7:76:8A:5F:FE:73:C8:16:3E:E2:8B:F8:B9:6B:07:9D:5E:0C:54:8A:77:A6:77\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\na=candidate:2417137320 1 udp 2113937151 192.168.199.128 57612 typ host generation 0 ufrag KwOQ network-cost 999\r\n"}`

But if I set offer and candiate in different time, it can't work.
```
{"type":"offer","sdp":"v=0\r\no=- 3110157978395432486 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:KwOQ\r\na=ice-pwd:yPaeFKtxkTrXUy7xVhhRP15s\r\na=ice-options:trickle\r\na=fingerprint:sha-256 EA:A1:E7:BF:C9:8C:66:74:01:E7:76:8A:5F:FE:73:C8:16:3E:E2:8B:F8:B9:6B:07:9D:5E:0C:54:8A:77:A6:77\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}

{"type":"offer","sdp":"a=candidate:2417137320 1 udp 2113937151 192.168.199.128 57612 typ host generation 0 ufrag KwOQ network-cost 999\r\n"}
```

I get the error messages is:
`peer-connection-app: Cannot parse remote description: no value`

If we support tickle, How to solve this question? 

Thank you @lgrahl

**Comment by lgrahl** [comment]
Like the WebRTC API for the Web, you cannot add new candidates as a sole offer. Call `rawrtc_peer_connection_add_ice_candidate`.

**Comment by lxlenovostar** [comment]
I test it in peer-connection.c , It's success.

Proceed as follows:
1.include some header files:
```
#include "../src/peer_connection/connection.h"
#include "../src/peer_connection_description/description.h"
```


2.add source codes
 ```
 // Get dict from JSON
        error = get_json_stdin(&dict);
        if (error) {
                do_exit = error == RAWRTC_CODE_NO_VALUE;
                return;
        }

         DEBUG_WARNING("what1.1\n");

        // Decode JSON
        error |= dict_get_entry(&sdp, dict, "candidate", ODICT_STRING, true);
        if (error) {
                DEBUG_WARNING("Invalid remote description\n");
                return;
        }

        struct rawrtc_peer_connection *connection = client->connection;
        struct rawrtc_peer_connection_description *remote_description = connection->remote_description;

        char* username_fragment;
         // Get username fragment from the remote ICE parameters
        int error = rawrtc_ice_parameters_get_username_fragment(&username_fragment, remote_description->ice_parameters);
        if (error) {
            DEBUG_WARNING(
                "Unable to retrieve username fragment, reason: %s\n", rawrtc_code_to_str(error));
            return ;
        }

        DEBUG_INFO("step1 mdeia_line_index:%d, mid:%s, username_fragment:%s\n", remote_description->media_line_index, remote_description->mid, username_fragment);

        struct rawrtc_peer_connection_ice_candidate* candidate;
        rawrtc_peer_connection_ice_candidate_create(&candidate, sdp, remote_description->mid, &remote_description->media_line_index, username_fragment);

        rawrtc_peer_connection_add_ice_candidate(connection, candidate);

        mem_deref(username_fragment);
        mem_deref(candidate);
        mem_deref(dict);

```
btw: I think we should add API which get mid and media_line_index in peer_connectionn.h, in this way, we don't need
include  `"../src/peer_connection/connection.h"` and  `"../src/peer_connection_description/description.h"` .
