### ISSUE TITLE
Media Channel/SRTP support

### ISSUE THREAD

**Issue by youaresoomean** [rawrtc/rawrtc#20]
How complicated would adding support for media channels be? Using NativeWebRTC is huge and rawtcs compactness is very attractive for our applications which involve streaming video from a native webrtc peer to browser clients.

**Comment by lxlenovostar** [comment]
Will SRTP be better than SCTP ? @lgrahl

**Comment by lgrahl** [comment]
They aren't comparable.

**Comment by lgrahl** [comment]
I'm open for PRs but audio/video is not on my agenda.
