### ISSUE TITLE
Handle SCTP restart

### ISSUE THREAD

**Issue by lgrahl** [rawrtc/rawrtc#50]
When does a SCTP restart occur? Will this happen in WebRTC at all? @tuexen

**Comment by tuexen** [comment]
An SCTP restart occurs, if an SCTP association is established between A and B. B might crash and reestablishes using the normal handshake a new association to A using the same port numbers. A will consider the association as being reset. From an application's point of view, this is simiar to a CONN-LOST followed by a CONN-UP notification.

**Comment by lgrahl** [comment]
So, this can happen in WebRTC if something crashes in B's SCTP stack and the association is not being teared down properly. But B can recover (DTLS & co have not crashed) and reconnect. Mhh, sounds like an extremely rare corner case to me. If there are no objections, I'll mark this as low priority.

**Comment by tuexen** [comment]
> On 19. Jun 2017, at 10:51, Lennart Grahl <notifications@github.com> wrote:
> 
> So, this can happen in WebRTC if something crashes in B's SCTP stack and the association is not being teared down properly. But B can recover (DTLS & co have not crashed) and reconnect. Mhh, sounds like an extremely rare corner case to me. If there are no objections, I'll mark this as low priority.
I agree.

Best regards
Michael

**Comment by lgrahl** [comment]
Moved to https://github.com/rawrtc/rawrtc-data-channel/issues/13
