### ISSUE TITLE
Handle SCTP send failed event

### ISSUE THREAD

**Issue by lgrahl** [rawrtc/rawrtc#51]
What should we do in such a case - close the channel or raise the error handler? Will this event be called for non-reliable messages that could not be delivered as well? @tuexen

**Comment by tuexen** [comment]
I think the WebRTC API has no way of "giving back messages to the application". So you don't need to subscribe to these events. In the case of SIGTRAN, where SCTP was originally developed for, it is an important feature to give these messages back such that the application can send them via a different association.

**Comment by lgrahl** [comment]
While it's not supported in the ORTC API to get the actual message that failed, we still could call the [`onerror` event handler](http://draft.ortc.org/#dom-rtcdatachannel-onerror) in case a message could not be delivered. I'm also fine with slightly extending the ORTC API in this case to attach the related message as well.

It's still not clear to me when an SCTP send failed event occurs and what other events are involved:
1. Is this event being raised for partially reliable messages?
2. Is this the only event being raised when a reliable message could not be delivered? Or are there other implicit events such as the association is being teared down (COMM_LOST)?

**Comment by tuexen** [comment]
The notification is sent when the association ungracefully terminates or if a message is abandoned in PR-SCTP.

**Comment by lgrahl** [comment]
Okay, thanks! That concludes we don't need to listen for this event (but I'll leave it in for debugging purposes).
