### ISSUE TITLE
Node.js bindings

### ISSUE THREAD

**Issue by daviddias** [rawrtc/rawrtc#8]
Just to be sure I understand correctly if Node.js bindings are built for this package, would this be 100% compatible with Browser Data Channels implementations?

**Comment by lgrahl** [comment]
It still needs a WebRTC-ORTC shim (converting WebRTC's SDP to ORTC objects and vice versa). But you can already use the ORTC API if you add node.js bindings. Ideally, they reflect the ORTC JS API (draft.ortc.org), so once adapterjs adds data channel support to their WebRTC-ORTC shim it should work out of the box.

Let me know if you need help - I'm very interested in bindings to other languages.

**Comment by lgrahl** [comment]
For your main question: RAWRTC can already talk to browsers, so the answe is yes. See #4 for instructions. I will add this to the readme shortly.

**Comment by diasdavid** [comment]
Oh, this is excellent @lgrahl! So rawrtc is a 'better' [wrtc](http://npmjs.org/wrtc) that runs everywhere and will also talk with the Edge browser (once they also have Data Channels).

Calling out @mafintosh and @feross as I believe they will be very interested in this. In fact, I know that @mafintosh has a lot of experience creating bindings for native addons :)

**Comment by lgrahl** [comment]
Be aware that this project is still in an early phase, so in case you're missing any functions that would block your progress, let me know. (There are a lot of getter/setter functions missing that are really easy to add but I had other priorities.) The C-API is already as near to the official ORTC JS API as possible.

**Comment by feross** [comment]
There are also other new RTC libraries that I just learned about, both are data-channel only:

- https://github.com/xhs/librtcdc
- https://github.com/chadnickbok/librtcdcpp

@lgrahl Any idea how `rawrtc` differs from these other projects?

**Comment by lgrahl** [comment]
Both libraries you mentioned use `libnice` which has a few issues:
* it depends on the GLib which is massive and has it's own problems, and
* it's LGPL-licensed, so you need to link it dynamically.

Both `librtcdc` and `librtcdcpp`:
* use threads for the various components,
* use `usrsctp`, not `usrsctp-neat` (which provides support for event loops),
* [handle data channel messages incorrectly (but all browsers do that as well)](https://lgrahl.de/articles/demystifying-webrtc-dc-size-limit.html),
* have no ORTC support, but
* have WebRTC support

RAWRTC:
* is slim as it only depends on `re`, `rew` and `usrsctp` which have no further dependencies,
* uses asynchronous I/O (one event loop on one thread does the job),
* handles data channel messages correctly (see link above),
* has ORTC support, and
* will have WebRTC support in the future (but it already works with a JS-shim on the browser side),
* currently lacks TURN and ICE-TCP support (this is high priority and will be the next thing to be added)

Hopefully I haven't forgotten anything major. :)

**Comment by feross** [comment]
Thanks for the detailed explanation!

Is it your intention to support only data channel? It's been my experience that libraries that aim to also support video/audio have had long compilation times and were unwieldy to work with.

**Comment by lgrahl** [comment]
I have no experience with audio/video support but the stack is built to be extendable. However, if audio/video will be added, it must be an optional feature that explicitly needs to be enabled during compilation time.

**Comment by notedit** [comment]
audio/video is far more complex than datachannel.   i am thinking make a golang binding after rawrtc have support turn.

**Comment by lgrahl** [comment]
@notedit Sounds good! Again, if anything blocks you from making progress, let me know. TURN support is planned and marked as high priority.

**Comment by feross** [comment]
@lgrahl I love that this library is data-channel first and video/audio will be an explicit compile-time opt-in. Thanks for the great work, and for solving the biggest need of WebRTC data channel users IMO

**Comment by lgrahl** [comment]
Btw. TURN support is nearing completion.

**Comment by Globik** [comment]
How to enable a rawrtc in to the code of your own? Must be event loop started in background?

**Comment by lgrahl** [comment]
@Globik Depends on your code entirely. If it's async, you can use the event loop. If it has blocking sections, you will need to [run the event loop in a different thread](https://github.com/creytiv/retest/blob/10d6cf54420f29d740235d7c068eb7c8b9f28dcb/src/remain.c). But please open a new issue if the question isn't related to the topic.

**Comment by lgrahl** [comment]
The [simple-peer test suite](https://github.com/feross/simple-peer/tree/master/test) would be a nice place to ensure basic support and verify bindings and the library work as expected for that use case.

**Comment by Globik** [comment]
For what this simple-peer? For communications between applications?
Or for a webRTC/ORTC gateway server?

**Comment by Globik** [comment]
Apropos, do you know that nodejs supports now abi compatible c code for its bindings? It means developers can now to write bindings using pure C. No need for a Cplusplus stuff. It's napi.h for nodejs addons.

**Comment by lgrahl** [comment]
> For what this simple-peer? For communications between applications? Or for a webRTC/ORTC gateway server?

Like I said, it's a good place to start to verify basic support. You don't need to use it or anything.

> Apropos, do you know that nodejs supports now abi compatible c code for its bindings?

Didn't know that but that sounds good. https://nodejs.org/api/n-api.html

**Comment by lgrahl** [comment]
Guidance for a Node.js binding:

I would very much recommend to precisely copy the [official WebRTC API](http://webrtc.github.io/). The C API of RAWRTC is very much leaning on that API anyway. It would also be extremely useful since JS apps could simply swap the underlying implementation. And it would be a significant step forward for testing (#38) as there are a whole [bunch of integration tests](https://github.com/web-platform-tests/wpt/tree/master/webrtc) for that API we could apply.

RAWRTC is single-threaded and uses a different event loop to Node (which I think is using libuv). Running RAWRTC inside of libuv is possible by adding libuv as an available event loop in the code base of [re](https://github.com/creytiv/re) and has already been done as an experiment in the network programming lab of the Münster University of Applied Sciences. But the branch would need updating and a bit of cleanup to get it upstream. Ping me if you're interested.

Alternatively, one could run RAWRTC's event loop in another thread (see #117) and pass events/data back and forth. This is likely much easier to begin with.

**Comment by Globik** [comment]
"But the branch would need updating and a bit of cleanup to get it upstream. Ping me if you're interested."
What does it mean?
Why are you not using the usrsctp-neat under the hood?

**Comment by lgrahl** [comment]
Not that I'm aware of. Someone ported the event loop to libuv which is likely preliminary necessary work: https://github.com/rawrtc/re/pull/7

**Comment by tchakabam** [comment]
Hi @lgrahl 

Nope, you don't need to port your event loop to libuv to craft node bindings :) NodeJS using libUV internally is a detail that is very far away from the level of abstraction at which one would create bindings via the ABI stable N-API ...

Even if you may have other motivations in general to use libuv as an event loop support, which may be good for implementation concerns of rawrtc, it shouldn't actually affect either way how it can be bound to V8 runtime at all, and NodeJS provides the wrappers for either type of lib, it be already async or blocking sync' API to be glue'd to it. 

That is something where I have seen and participated in a few cases to share some experience. 

You may have to take different approaches to solve the case of a lib exposing a blocking API in order for it to be called non-blocking from V8 land. There are different solutions for that, either through N-API (in C++) or in JS worker land event. 

So, to be clear: None of them needing you to change the actual native lib bound to!
