### ISSUE TITLE
rawrtc_data_channel_send  support Asynchronous mode

### ISSUE THREAD

**Issue by lxlenovostar** [rawrtc/rawrtc#95]
This function rawrtc_data_channel_send  supports asynchronous mode? I know rawrtc_data_channel_send use usrsctp_sendv().  Or we can modify the code and let rawrtc_data_channel_send() support it. 

Thank you.

**Comment by lgrahl** [comment]
It is non-blocking and always has been. 😉

**Comment by lxlenovostar** [comment]
I want to send data more than 1MB by datachannel, If  `rawrtc_data_channel_send ` is sync,  It maybe affect http download.

Thank you.

**Comment by lgrahl** [comment]
You can queue as much data as you like and the function just returns. So, it works in the same way the JS API works. The long async blocking happens in `data-channel-sctp´ because 1 GiB of memory is being free'd at once.

**Comment by lxlenovostar** [comment]
Thank you
