### ISSUE TITLE
Advice on cross-compiling for ARM/mips

### ISSUE THREAD

**Issue by SahAssar** [rawrtc/rawrtc#96]
Hi,

Do you have any advice on how to crosscompile rawrtc for ARM and mips? I'd like to try running this on some IOT devices.

Thanks!

**Comment by lgrahl** [comment]
The main problem is that we have three different build systems for the dependencies and the `make-dependencies.sh` script hasn't been written with cross compiling in mind. But I'm facing the same problem soon and I know of at least two other people who are interested in this as well. I'm in contact with someone who volunteered to fix this problem, so I'll ping that person as I myself don't have much experience in this topic.

Even though it's far less than ideal, you *could* compile on the platform itself. It will be somewhat bearable if a modern OpenSSL version is installed.

**Comment by SahAssar** [comment]
Thanks! I'll look into compiling on-device (or similar dev-devices) for the time being and If you need any tester for arm/mips devices in the future please let me know :)

**Comment by lgrahl** [comment]
Sure, I'll come back to you for testing. Also, if you know some people that have experience with cross compiling who would like to contribute to fix this problem in RAWRTC, I'd be very happy.

**Comment by JesApp** [comment]
RawRTC cross-compiles for [Lego Mindstorms EV3](https://education.lego.com/en-us/shop/mindstorms%20ev3) – which is an ARM-based system – whithout a problem. 

I'm using [ev3devs](http://www.ev3dev.org/) cross-compilation [docker container](https://hub.docker.com/r/ev3dev/debian-jessie-cross/), which is basically debian jessie plus an ARM cross-compilation toolchain. All that's required is setting the evironment variables `CC=arm-linux-gnueabi-gcc` and `CCX=arm-linux-gnueabi-g++`. 

For more info, check their [Dockerfile](https://github.com/ev3dev/docker-cross/blob/master/ev3dev-jessie/debian-jessie-cross.dockerfile).

**Comment by JesApp** [comment]
About `make-dependencies.sh`: First off, it works just fine as described above. That being said, I recently learned about the [ExternalProject](https://cmake.org/cmake/help/v3.11/module/ExternalProject.html) feature of cmake and used it for a similar purpose as your `make-dependencies.sh`. 

It's a very nice feature that makes things a bit more portable than a custom script, also just easier in general. At least for usrsctp, libre and librew using this should be no problem. As for the stuff you have to pull to get the right version of OpenSSL - that would probably be a lot uglier. Although it's not exactly pretty right now either.

**Comment by lgrahl** [comment]
We've switched to Meson and it's much, much, much easier to cross-compile now.

See: https://mesonbuild.com/Cross-compilation.html

If you need help, let me know.
